<!DOCTYPE html>
<html lang="cs-cz" dir="ltr">
  <head>
    <meta charset="UTF-8" />
      <?php include_once("head.html") ?>
    <title>SOLANSKÝ s.r.o. Nákladní autodoprava | O společnosti</title>
  </head>
  
  <body>
    
    <!--[if lt IE 9]>
      <script src="../files/js/html5shiv.js"></script>
      <script src="../files/js/respond.min.js"></script>
    <![endif]-->
    
    <div id="box" class="container">

      <div id="navigator" class="navbar navbar-default" role="navigation">
        <div class="nav navbar-nav navbar-header">
          <span class="navbar-brand" >SOLANSKÝ s.r.o.</span>
        </div> <!-- div navbar-header -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <!--<li><a href="onas.phtml">O nás</a></li>-->
            <li class="active"><a href="index.phtml">O společnosti</a></li>
            <li><a href="vozovypark.phtml">Vozový park</a></li>
            <li><a href="kamenivo.phtml">Prodej kameniva</a></li>
            <li><a href="reference.phtml">Reference</a></li>
            <li><a href="kontakty.phtml">Kontakty</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../cz/index.phtml">cz</a></li> 
            <li class="navbar-text">|</li>
            <li><a href="../en/contacts.phtml">en</a></li>
            <li class="navbar-text">|</li>
            <li><a href="../de/index.phtml">de</a></li>
          </ul>
        </div><!-- div navbar-collapse -->
      </div>

      <!-- 
      <div id="myCarousel" class="carousel slide">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="item active">
            <img src="../files/img/sro001.jpg" alt="First slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Nabízíme široký sortiment služeb</h1>
                <p> Vnitrostátní a mezinárodní spedice a přeprava sypkých
                materiálů, opravy silničních vozidel, prodej kameniva, 
                štěrku a písku a další.</p>
                <p><a class="btn btn-large btn-primary" href="sluzby.phtml">Více o službách</a></p>
              </div>
            </div>
          </div>
          <div class="item">
            <img src="../files/img/PA041640.JPG" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Převážíme již od roku 1991</h1>
                <p>Za ty roky jsme vyměnili desítky vozů. Podívejte se,
                jakým technickým vybavením disponujeme dnes.</p>
                <p><a class="btn btn-large btn-primary" href="vybaveni.phtml">Více o technickém vybavení</a></p>
              </div>
            </div>
          </div>
          <div class="item">
            <img src="../files/img/sro003.jpg" alt="Third slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Neváhejte a kontaktujte nás</h1>
                <p></p>
                <p><a class="btn btn-large btn-primary" href="kontakty.phtml">Přejít na kontakty</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
      </div>
      --> 

      <div class="jumbotron">
      </div> <!-- class="jumbotron" -->

      <div id="onas" class="container container-padding">
        <h1 class="page-header">O společnosti</h1>
        <p><strong>SOLANSKÝ s.r.o.</strong> je česká společnost, specializující se na
        <strong>vnitrostátní a mezinárodní silniční přepravu sypkých materiálů</strong>, která
        byla založena v roce 1991. V současné době firma vlastní 35 sklápěcích
        nákladních vozidel, díky kterým provádí přepravu do všech státu
        Evropské unie i mimo ní (Chorvatsko, Černá Hora, Albánie, Bosna a
        Hercegovina atd.).</p>
        <h2 class="page-header">Historie</h2>
        <p>Dopravní firma SOLANSKÝ s.r.o., jejíž hlavní specializací je
        přeprava sypkých hmot, jako jsou štěrky, písky, drcené kamenivo a
        podobně, byla založena panem Solanským v roce 1991 pod názvem Zdeněk
        Solanský – autodoprava.</p>
        <p>Firma začínala podnikat s jedním vozidlem značky LIAZ. V počátcích
        podnikání se vozidla této značky stala páteří vozového parku. Postupně
        s přibývajícím množstvím zakázek, začal majitel firmy rozšiřovat vozový
        park o nákladní automobily dalších značek, především Volvo a DAF.</p>
        <p>Další krok vpřed v podnikání pana Solanského znamenal rok 2003, kdy
        společně se svojí ženou Ivanou založil společnost SOLANSKÝ s.r.o.. Nově
        vzniklý subjekt převzal všechny aktivity a pole působnosti rozšířil o
        další služby jako je velkoobchod a maloobchod se sypkými hmotami,
        maloobchod s motorovými vozidly a jejich příslušenství, zasilatelství a
        opravy silničních vozidel a karoserií.</p>
        <p>V současnosti společnost SOLANSKÝ s.r.o. provozuje 35 nákladních
        vozidel značky Volvo, MAN, DAF a Mercedes-Benz.</p>
        <h2 class="page-header">Náš kolektiv</h2> 
        <p>
        <a href="../files/img/Koliba.jpg"><img src="../files/img/Koliba.jpg" alt="Fotka zaměstnanců firmy Solanský s.r.o."></a>
        </p>
      </div><!-- div onas -->

      <?php include_once("footer.html") ?>

    </div> <!-- div container -->
  </body> 
</html>
