<!DOCTYPE html>
<html lang="cs-cz" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <?php include_once("head.html") ?>
    <title>SOLANSKÝ s.r.o. Nákladní autodoprava | Prodej kameniva</title>
  </head>
  
  <body>

    <!--[if lt IE 9]>
      <script src="../files/js/html5shiv.js"></script>
      <script src="../files/js/respond.min.js"></script>
    <![endif]-->

    <div id="box" class="container">

      <div id="navigator" class="navbar navbar-default" role="navigation">
        <div class="nav navbar-nav navbar-header">
          <span class="navbar-brand" >SOLANSKÝ s.r.o.</span>
        </div> <!-- div navbar-header -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <!--<li><a href="onas.phtml">O nás</a></li>-->
            <li><a href="index.phtml">O společnosti</a></li>
            <li><a href="vozovypark.phtml">Vozový park</a></li>
            <li class="active"><a href="kamenivo.phtml">Prodej kameniva</a></li>
            <li><a href="reference.phtml">Reference</a></li>
            <li><a href="kontakty.phtml">Kontakty</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../cz/index.phtml">cz</a></li> 
            <li class="navbar-text">|</li>
            <li><a href="../en/contacts.phtml">en</a></li>
            <li class="navbar-text">|</li>
            <li><a href="../de/index.phtml">de</a></li>
          </ul>
        </div><!-- div navbar-collapse -->
      </div>

      <div class="jumbotron">
      </div> <!-- class="jumbotron" -->

      <div id="kamenivo" class="container container-padding">
        <h1 class="page-header">Prodej kameniva</h1>
        <p>
        <span class="sestnact">Společnost nabízí dopravu a prodej drceného kameniva, těženého kameniva a písku:</span>
        </p>
        <h2>Drcené kamenivo</h2>
        <div class="container">
          <div class="col-lg-12">
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 text-center">
              <img src=../files/img/kamenivo/DK4-8.JPG alt="DK4-8" />
              <br />
              <h5><strong>DK 4-8</strong></h5>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 text-center">
              <img src=../files/img/kamenivo/DK16-32.JPG alt="DK16-32" />
              <br />
              <h5><strong>DK 16-32</strong></h5>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 text-center">
              <img src=../files/img/kamenivo/DK32-63.JPG alt="DK32-63" />
              <br />
              <h5><strong>DK 32-63</strong></h5>
            </div>
          </div>
        </div>
        <h2>Těžené kamenivo</h2>
        <div class="container">
          <div class="col-lg-12">
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 text-center">
              <img src=../files/img/kamenivo/TK0-4.JPG alt="TKO-4" />
              <br />
              <h5><strong>TK 0-4</strong></h5>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 text-center">
              <img src=../files/img/kamenivo/TK16-22.JPG alt="TK16-22" />
              <br />
              <h5><strong>TK 16-22</strong></h5>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 text-center">
              <img src=../files/img/kamenivo/HustopeceTK0-22.JPG alt="TKO-22" />
              <h5><strong>TK 0-22</strong></h5>
            </div>
          </div>
        </div>
        <h2>Písek</h2>
        <div class="container">
          <div class="col-lg-12">
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 text-center">
              <img src=../files/img/kamenivo/Pisek.JPG alt="Pisek" />
              <h5><strong>Písek</strong></h5>
            </div>
          </div>
        </div>


      </div><!-- div sluzby -->
      <?php include_once("footer.html") ?>
    </div> <!-- id="box" class="container" -->
  </body> 
</html>
