<!DOCTYPE html>
<html lang="cs-cz" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <?php include_once("head.html") ?>
    <title>SOLANSKÝ s.r.o. Nákladní autodoprava | Reference</title>
  </head>
  
  <body>

    <!--[if lt IE 9]>
      <script src="../files/js/html5shiv.js"></script>
      <script src="../files/js/respond.min.js"></script>
    <![endif]-->

    <div id="box" class="container">
      <div id="navigator" class="navbar navbar-default" role="navigation">
        <div class="nav navbar-nav navbar-header">
          <span class="navbar-brand" >SOLANSKÝ s.r.o.</span>
        </div> <!-- div navbar-header -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <!--<li><a href="onas.phtml">O nás</a></li>-->
            <li><a href="index.phtml">O společnosti</a></li>
            <li><a href="vozovypark.phtml">Vozový park</a></li>
            <li><a href="kamenivo.phtml">Prodej kameniva</a></li>
            <li class="active"><a href="reference.phtml">Reference</a></li>
            <li><a href="kontakty.phtml">Kontakty</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../cz/index.phtml">cz</a></li> 
            <li class="navbar-text">|</li>
            <li><a href="../en/contacts.phtml">en</a></li>
            <li class="navbar-text">|</li>
            <li><a href="../de/index.phtml">de</a></li>
          </ul>
        </div><!-- div navbar-collapse -->
      </div>
      
      <div class="jumbotron">
      </div> <!-- class="jumbotron" -->
    
      <div id="reference" class="container container-padding">
        <h1 class="page-header">Reference</h1>
        <p>
        ADM, a.s.<br />
        ALPINE Bau CZ s.r.o.<br />
        BEST, a.s.<br />
        CEMEX Czech Republic, s.r.o.<br />
        Českomoravský štěrk, a.s.<br />
        EUROVIA CS, a.s.<br />
        HOKA, spol. s r.o.<br />
        KALMAN TRADE s.r.o.<br />
        METALIMEX a.s.<br />
        MORAVIA STEEL a.s.<br />
        OKD, a.s.<br />
        SATES MORAVA spol. s r.o.<br />
        Stavebniny Kozelský a Kozelský s.r.o.<br />
        SWIETELSKY stavební s.r.o.<br />
        UHLOBESKYD - obchod s palivy, spol. s r. o.<br />
        Wienerberger cihlářský průmysl, a.s.<br />
        a další…
        </p>
                </div><!-- div vybaveni -->
      <?php include_once("footer.html") ?>
    </div> <!-- id="box" class="container" -->
  </body> 
</html>
