<!-- NAVIGACE
index.phtml 
onas.phtml 
sluzby.phtml
vybaveni.phtml
kontakty.phtml -->

<!DOCTYPE html>
<html lang="cs-cz" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <?php include_once("head.html") ?>
    <title>Solanský s.r.o. Nákladní autodoprava | Služby</title>
  </head>
  
  <body>
    <div id="box" class="container">
      <?php include_once("header.html") ?>

      <div class="jumbotron">
      </div> <!-- class="jumbotron" -->
      
      <div id="sluzby" class="container container-padding">
        <h1 class="page-header">Nabízíme</h1>
        <p>
          <ul>
            <li>vnitrostátní a mezinárodní přeprava sypkých materiálů</li>
            <li>spedice vnitrostátní a mezinárodní</li>
            <li>opravy silničních vozidel</li>
            <li>prodej náhradních dílů vozidel</li>
            <li>prodej kameniva, štěrku a písku:</li>
             </ul>
          <div class="container">
            <div class="container col-md-3 col-sm-3 text-center">
              <img src=../files/img/kamenivo/DK4-8.JPG height=150 width=200>
              <br />
              <h5><strong>DK4-8</strong></h5>
            </div>
            <div class="container col-md-3 col-sm-3 text-center">
              <img src=../files/img/kamenivo/DK16-32.JPG height=150 width=200>
              <br />
              <h5><strong>DK16-32</strong></h5>
            </div>
            <div class="container col-md-3 col-sm-3 text-center">
              <img src=../files/img/kamenivo/DK32-63.JPG height=150 width=200>
              <br />
              <h5><strong>DK32-63</strong></h5>
            </div>
          </div>
          
          <div class="container">
            <div class="container col-md-3 col-md-offset-3 text-center">
              <img src=../files/img/kamenivo/TK0-4.JPG height=150 width=200>
              <br />
              <h5><strong>TK0-4</strong></h5>
              <br />
              <img src=../files/img/kamenivo/Pisek.JPG height=150 width=200>
              <br />
              <h5><strong>Písek</strong></h5>
            </div>
            <div class="container col-md-3 col-sm-3 text-center">
              <img src=../files/img/kamenivo/TK16-22.JPG height=150 width=200>
              <br />
              <h5><strong>TK016-22</strong></h5>
              <br />
              <img src=../files/img/kamenivo/HustopeceTK0-22.JPG height=150 width=200>
              <br />
              <h5><strong>Hustopece TK0-22</strong></h5>
            </div>
          </div>
        </p>
      </div><!-- div sluzby -->
      <?php include_once("footer.html") ?>
    </div> <!-- id="box" class="container" -->
  </body> 
</html>
