<!-- NAVIGACE
index.phtml 
onas.phtml 
sluzby.phtml
vybaveni.phtml
kontakty.phtml -->

<!DOCTYPE html>
<html lang="cs-cz" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <?php include_once("head.html") ?>
    <title>Solanský s.r.o. Nákladní autodoprava | Technické vybavení</title>
  </head>
  
  <body>
    <div id="box" class="container">
      <?php include_once("header.html") ?>

      <div class="jumbotron">
      </div> <!-- class="jumbotron" -->
    
      <div id="vybaveni" class="container container-padding">
        <h1 class="page-header">Technické vybavení</h1>
        <p>
              <img src=../files/img/sro007.jpg alt="Nákladní vozidla firmy Solanský s.r.o." />
          <ul>	
            <li>30 nákladních vozidel - značky VOLVO, MAN, MERCEDES</li>
            <li>20 velkoobjemových sklápěcích návěsů (40 - 60m2)</li>
            <li>5 sklápěcích návěsů 30m2</li>
            <li>5x souprava návěs + auto</li>
            <li>návěs s posuvnou podlahou (walking floor)</li>
          </ul>
        </p>
      </div><!-- div vybaveni -->
      <?php include_once("footer.html") ?>
    </div> <!-- id="box" class="container" -->
  </body> 
</html>
