<!-- NAVIGACE
index.phtml 
about_us.phtml 
services.phtml
equipment.phtml
contacts.phtml -->
 
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <?php include_once("head.html") ?>
    <title>Solanský s.r.o. Nákladní autodoprava | Contacts</title>
  </head>
  
  <body>
    <div id="box" class="container">
      <?php include_once("header.html") ?>

      <div class="jumbotron">
      </div> <!-- class="jumbotron" -->
      
      <div id="kontakty" class="container container-padding">
        <h1 class="page-header">Contacts</h1>
        <div id="sidlo" class="container">
          <div class="container col-md-1 col-sm-1">
          </div><!-- class="container col-md-2">-->
          <div class="container col-md-4 col-sm-4">
            <address>
              <h4>Company Headquarters / Sale of materials:</h4>
              <dl class="dl-horizontal">
                <dt>address</dt>
                <dd>Vigantice 278</dd>
                <dt></dt>
                <dd>756 61</dd>
                <dt></dt>
                <dd>Czech republic</dd>
                <dt>Tel.</dt>
                <dd>+420 571 656 440</dd>
              </dl>
              <h4>Head Office:</h4>
              <dl class="dl-horizontal">
                <dt>address</dt>
                <dd>Tylovice 2050</dd>
                <dt></dt>
                <dd>756 61 Rožnov pod Radhoštěm</dd>
                <dt></dt>
                <dd>Czech republic</dd>
                <dt>Tel./Fax</dt>
                <dd>+420 571 656 444</dd>
              </dl>
            </address>
          </div><!-- class="container col-md-4">-->
          <div class="container col-md-5 col-sm-5">
            <?php include_once("mapa.html") ?>
          </div><!-- class="container col-md-6">-->
        </div><!-- div sidlo  class="container"-->
        
        <h2 class="page-header">Individual contacts</h2>
        
        <div id="osoby" class="container">
          <div class="container">
            <div class="container col-md-6">
              <dl class="dl-horizontal">
                <dt></dt>
                <dd><strong>Zdeněk Solanský</strong></dd>
                <dt></dt>
                <dd><i>managing director</i></dd>
                <dt>Mob.</dt>
                <dd>+420 602 728 613</dd>
                <dt>Tel.</dt>
                <dd>+420 571 656 444</dd>
                <dt>e-mail</dt>
                <dd>solanskyzdenek@quick.cz</dd>
              </dl>
            </div><!-- class="container col-md-6">-->
            <div class="container col-md-6">
              <dl class="dl-horizontal">
                <dt></dt>
                <dd><strong>Martin Solanský</strong></dd>
                <dt></dt>
                <dd><i>head of auto service</i></dd>
                <dt>Mob.</dt>
                <dd>+420 602 575 025</dd>
                <dt>e-mail</dt>
                <dd>martin.solansky@gmail.com</dd>
              </dl>
            </div><!-- class="container col-md-6">-->
          </div><!-- div container-->
            
          <div class="container">
            <div class="container col-md-6">
              <dl class="dl-horizontal">
                <dt></dt>
                <dd><strong>Zdeněk Krhut</strong></dd>
                <dt></dt>
                <dd><i>head dispatcher for international and national transport</i></dd>
                <dt>Mob.</dt>
                <dd>+420 724 178 909</dd>
                <dt>Tel.</dt>
                <dd>+420 571 656 440</dd>
                <dt>e-mail</dt>
                <dd>solanskydoprava@quick.cz</dd>
              </dl>
              <dl class="dl-horizontal">
            </div><!-- class="container col-md-6">-->
            <div class="container col-md-6">
              <dl class="dl-horizontal">
                <dt></dt>
                <dd><strong>Václav Zářický</strong></dd>
                <dt></dt>
                <dd><i>dispatcher for international transport</i></dd>
                <dt>Mob.</dt>
                <dd>+420 724 501 405</dd>
                <dt>Tel.</dt>
                <dd>+420 571 656 440</dd>
                <dt>email</dt>
                <dd>solanskydoprava@quick.cz</dd>
              </dl>
            </div><!-- class="container col-md-6">-->
          </div><!-- div container-->
            
          <div class="container">
            <div class="container col-md-6">
              <dl class="dl-horizontal">
                <dt></dt>
                <dd><strong>Rudolf Vajgl</strong></dd>
                <dt></dt>
                <dd><i>dispatcher for national transport, billing</i></dd>
                <dt>Mob.</dt>
                <dd>+420 724 124 705</dd>
                <dt>e-mail</dt>
                <dd>rudavajgl@gmail.com</dd>
                <dt></dt>
              </dl>
            </div><!-- class="container col-md-6">-->
            <div class="container col-md-6">
              <dl class="dl-horizontal">
                <dd><strong>Ivana Solanská</strong></dd>
                <dt></dt>
                <dd><i>accountant, billing</i></dd>
                <dt>Mob.</dt>
                <dd>+420 724 178 910</dd>
              </dl>
              <dl>
            </div><!-- class="container col-md-6">-->
          </div><!-- div container-->
        </div><!-- div osoby class="container"-->
      </div><!-- div kontakty -->
      
      <?php include_once("contact_us.html") ?>
      <?php include_once("footer.html") ?>

    </div> <!-- id="box" class="container" -->
  </body> 
</html>
