<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <?php include_once("head.html") ?>
    <title>Solanský s.r.o. Nákladní autodoprava | Technical equipment</title>
  </head>
  
  <body>

    <!--[if lt IE 9]>
      <script src="../files/js/html5shiv.js"></script>
      <script src="../files/js/respond.min.js"></script>
    <![endif]-->

    <div id="box" class="container">
      <?php include_once("header.html") ?>

      <div class="jumbotron">
      </div> <!-- class="jumbotron" -->
    
      <div id="vybaveni" class="container container-padding">
        <h1 class="page-header">Technical equipment</h1>
        <p>
          <img src=../files/img/sro007.jpg alt="Company's trucks" />
          <br />
          <br />
          We're sorry, this page is under construction.
        </p>
<!--        <ul>	
          <li>30 nákladních vozidel - značky VOLVO, MAN, MERCEDES</li>
          <li>20 velkoobjemových sklápěcích návěsů (40 - 60m2)</li>
          <li>5 sklápěcích návěsů 30m2</li>
          <li>5x souprava návěs + auto</li>
          <li>návěs s posuvnou podlahou (walking floor)</li>
        </ul>-->
      </div><!-- div vybaveni -->
      <?php include_once("footer.html") ?>
    </div> <!-- id="box" class="container" -->
  </body> 
</html>
