<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <meta charset="UTF-8" />
      <?php include_once("head.html") ?>
    <title>Solanský s.r.o. Nákladní autodoprava | Introduction</title>
  </head>
  
  <body>
    <div id="box" class="container">
    <?php include_once("header.html") ?>

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <img src="../files/img/sro001.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>We are offering a wide range of services</h1>
<!--              <p> Vnitrostátní a mezinárodní spedice a přeprava sypkých materiálů, opravy silničních vozidel, prodej kameniva, štěrku a písku a další.</p>-->
              <p><a class="btn btn-large btn-primary" href="services.phtml">More about services</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="../files/img/sro002.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>We are transporting from 1991</h1>
              <p>We changed tens of truck during over the years. See
              what technical equipment we have today.</p>
              <p><a class="btn btn-large btn-primary" href="equipment.phtml">More about technical equipment</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="../files/img/sro003.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Please do not hesitate and contact us</h1>
              <p></p>
              <p><a class="btn btn-large btn-primary" href="contacts.phtml">Move to Contacts</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->



    <div id="onas" class="container container-padding">
      
      <h1 class="page-header">About company</h1>
      <p>
        We're sorry, this page is under construction. 
<!--        This text should be in English. 
        Firma Zdeněk Solanský - autodoprava byla založena v roce 1991.
        Nejprve se zabývala převážně přepravou kameniva a štěrku. Krok
        vpřed nastal v roce 2003, kdy byla založena firma SOLANSKÝ s.r.o..
        Nově vzniklý subjekt převzal všechny aktivity vyplývající z
        předchozí činnosti a svoje pole působnosti rozšířil o přepravu
        velkoobjemových sklápěcích návěsů a návěsů s posuvnou podlahou
        (walking floor).<br />

        V současnosti provádíme přepravu do všech států EU a také do států
        mimo EU, jako jsou například Chorvatsko, Černá Hora, Albánie,
        Bosna a Hercegovina a další státy.<br />

        Dnes firma vlastní 30 nákladních automobilů, z toho 20
        velkoobjemových sklápěcích návěsů, a zabývá se prodejem kameniva,
        štěrku a písku.-->
      </p>
    </div><!-- div onas -->
    <?php include_once("footer.html") ?>

      </div> <!-- div container -->
  </body> 
</html>
