<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <?php include_once("head.html") ?>
    <title>Solanský s.r.o. Nákladní autodoprava | Services</title>
  </head>
  
  <body>
    <div id="box" class="container">
      <?php include_once("header.html") ?>

      <div class="jumbotron">
      </div> <!-- class="jumbotron" -->
      
      <div id="sluzby" class="container container-padding">
        <h1 class="page-header">We offer</h1>
          <ul>
            <li>international and national transport of bulk materials</li>
            <li>spedice vnitrostátní a mezinárodní</li>
            <li>opravy silničních vozidel</li>
            <li>prodej náhradních dílů vozidel</li>
            <li>prodej kameniva, štěrku a písku:</li>
             </ul>
          
          <div class="container">
            <div class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-5 col-xs-offset-1 text-center">
              <img src=../files/img/kamenivo/DK4-8.JPG alt="DK4-8" />
              <br />
              <h5><strong>DK4-8</strong></h5>
              <img src=../files/img/kamenivo/TK0-4.JPG alt="TKO-4" />
              <br />
              <h5><strong>TK0-4</strong></h5>
              <img src=../files/img/kamenivo/Pisek.JPG alt="Sand" />
              <h5><strong>Sand</strong></h5>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-5 text-center">
              <img src=../files/img/kamenivo/DK16-32.JPG alt="DK16-32" />
              <br />
              <h5><strong>DK16-32</strong></h5>
              <img src=../files/img/kamenivo/TK16-22.JPG alt="TK16-22" />
              <br />
              <h5><strong>TK016-22</strong></h5>
              <img src=../files/img/kamenivo/HustopeceTK0-22.JPG alt="TKO-22" />
              <h5><strong>Hustopece TK0-22</strong></h5>
            </div>
            
            <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-4 col-sm-offset-1 col-xs-5 col-xs-offset-1 text-center">
              <img src=../files/img/kamenivo/DK32-63.JPG alt="DK32-63" />
              <br />
              <h5><strong>DK32-63</strong></h5>
            </div>
          </div>
      </div><!-- div sluzby -->
      <?php include_once("footer.html") ?>
    </div> <!-- id="box" class="container" -->
  </body> 
</html>
