<!-- NAVIGACE
index.phtml 
onas.phtml 
sluzby.phtml
vybaveni.phtml
kontakty.phtml -->

<!DOCTYPE html>
<html lang="cs-cz" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <div id="navigator" class="container opacity">
      <?php include_once("head.html") ?>
    </div><!-- div container -->
    </div>
    <title>Solanský s.r.o. Nákladní autodoprava | Úvod</title>
  </head>
  
  <body>
    <div id="box" class="container">
    <?php include_once("header_index.html") ?>

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <img src="files/img/sro001.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Převážíme již od roku 1991</h1>
              <p>Naše firma se nejprve zabývala převážně přepravou kameniva a štěrku.</p>
              <p><a class="btn btn-large btn-primary" href="onas.phtml">Více o firmě</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="files/img/sro002.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Nabízíme široký sortiment služeb</h1>
              <p> Vnitrostátní a mezinárodní spedice a přeprava sypkých materiálů, opravy silničních vozidel, prodej kameniva, štěrku a písku a další.</p>
              <p><a class="btn btn-large btn-primary" href="sluzby.phtml">Více o službách</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="files/img/sro003.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Neváhejte a kontaktujte nás</h1>
              <p></p>
              <p><a class="btn btn-large btn-primary" href="kontakty.phtml">Přejít na kontakty</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->



    <div id="onas" class="container container-padding">
      
      <h1 class="page-header">O firmě</h1>
      <p>
        Firma Zdeněk Solanský - autodoprava byla založena v roce 1991.
        Nejprve se zabývala převážně přepravou kameniva a štěrku. Krok
        vpřed nastal v roce 2003, kdy byla založena firma SOLANSKÝ s.r.o..
        Nově vzniklý subjekt převzal všechny aktivity vyplývající z
        předchozí činnosti a svoje pole působnosti rozšířil o přepravu
        velkoobjemových sklápěcích návěsů a návěsů s posuvnou podlahou
        (walking floor).<br />

        V současnosti provádíme přepravu do všech států EU a také do států
        mimo EU, jako jsou například Chorvatsko, Černá Hora, Albánie,
        Bosna a Hercegovina a další státy.<br />

        Dnes firma vlastní 30 nákladních automobilů, z toho 20
        velkoobjemových sklápěcích návěsů, a zabývá se prodejem kameniva,
        štěrku a písku.
      </p>
    </div><!-- div onas -->
    <?php include_once("footer.html") ?>

      </div> <!-- div container -->
  </body> 
</html>
