<!-- NAVIGACE
index.phtml 
onas.phtml 
sluzby.phtml
vybaveni.phtml
kontakty.phtml -->

<!DOCTYPE html>
<html lang="cs-cz" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <?php include_once("head.html") ?>
    <title>Solanský s.r.o. Nákladní autodoprava | Služby</title>
  </head>
  
  <body>
    <div id="box" class="container">
      <?php include_once("header.html") ?>

      <div class="jumbotron">
      </div> <!-- class="jumbotron" -->
      
      <div id="sluzby" class="container container-padding">
        <h1>Nabízíme</h1>
        <p>
          <ul>
            <li>vnitrostátní a mezinárodní přeprava sypkých materiálů</li>
            <li>spedice vnitrostátní a mezinárodní</li>
            <li>opravy silničních vozidel</li>
            <li>prodej náhradních dílů vozidel</li>
          </ul>
        </p>
      </div><!-- div sluzby -->
      <?php include_once("footer.html") ?>
    </div> <!-- id="box" class="container" -->
  </body> 
</html>
